apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: questions
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: questions
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: questions
  service:
    port: 8080
    targetPort: 8080
    trafficPolicy:
      tls:
        mode: DISABLE
    retries:
      attempts: 1
      perTryTimeout: 1s
      retryOn: "gateway-error,connect-failure,refused-stream"
  canaryAnalysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        threshold: 99
        interval: 1m
      - name: request-duration
        threshold: 500
        interval: 30s
