apiVersion: v1
kind: Service
metadata:
  name: &app surveys
  labels:
    app: *app
    service: too-many-surveys-service
spec:
  type: NodePort
  selector:
    app: *app
  ports:
    - name: http-api
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: &app surveys
  labels:
    app: *app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - name: surveys
          image: surveys:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "250m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "250Mi"
          ports:
            - containerPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: &app surveys
  labels:
    app: *app
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: *app
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 200Mi
