apiVersion: v1
kind: Service
metadata:
  name: questions
  labels:
    app: questions
spec:
  type: ClusterIP
  selector:
    app: questions
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
