apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: questions-virtual-service
spec:
  hosts:
  - questions
  http:
  - name: "target-martins-route"
    match:
    - headers:
        user:
          exact: martins
    route:
    - destination:
        host: questions
        subset: v3
      weight: 100
  - name: "questions-version-routes"
    route:
    - destination:
        host: questions
        subset: v1
      weight: 90
    - destination:
        host: questions
        subset: v2
      weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: questions-destinations
spec:
  host: questions
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
